### PR TITLE
Network: fix racy behavior of backoff persist on shutdown

### PR DESCRIPTION
**Pull request by reinkrul**
The problem was that `openOutboundStream`, a goroutine which blocks until the gRPC connection is closed, tried to reset the backoff timer after the storage engine already shut down. The function is (through intermediates) called by `outboundConnector.start` in a goroutine, and while the component has a `stop()` function, it doesn't wait until the goroutine exits. So what happened, was:

- Connection is active (goroutine blocked by `openOutboundStream()`)
- Kill signal, tells gRPC connections (through context cancellation) to shut down
- `openOutboundStream()` unblocks
- Meanwhile storage engine already shut down, since network module didn't wait until all subcomponents were shut down
- `openOutboundStream()` tries to reset backoff, which fails and renders an error

Fixed this by letting `outboundConnector.stop()` (called by `grpcConnectionManager.Stop()`) block the connector loop has stopped. To let current connection attempts (e.g. attempts to dead hosts, which may take a few seconds to time-out) not block shutdown, `outboundConnector.tryConnect()` now gets passed the context used to cancel the connector loop.

Also added logging exemptions to avoid logging `context.Canceled` as errors (they're normal shutdown artifacts).

Requires https://github.com/nuts-foundation/nuts-node/pull/1901

### CODE REVIEW

**Comment by reinkrul** [comment]
PR will be superseded by refactor of dialing components; https://github.com/nuts-foundation/nuts-node/pull/1874 (in which it will also be fixed)

**Comment by gerardsn** [comment]
> PR will be superseded by refactor of dialing components; #1874 (in which it will also be fixed)

`transport/v2` is not covered by #1874, `transport/grpc` still leaks go routines from `conn` (connection.go)

**Comment by reinkrul** [comment]
Fixes in `transport/v2` were already on master.

**Comment by reinkrul** [comment]
Fixes in `transport/v2` were already on master.

**Pull request closed without merging**
