### PR TITLE
change all refs from selfsigned to employeeid

### PR DESCRIPTION
**Pull request by woutslakhorst**
urls used `employeeid` but other references used `selfsigned`. All (but the packages) now use `employeeid` as the name of the means.

### CODE REVIEW

**Comment by gerardsn** [comment]
urls are part of an internal service, why not change those?

**Comment by woutslakhorst** [comment]
@stevenvegt , your thoughts?

**Review by reinkrul — APPROVED** [review]
Not opposed to the changes, but the Package is still called selfsigned, does that make sense?

**Review by stevenvegt — APPROVED** [review]
LGTM

**Pull request merged**
