### PR TITLE
add roadmap

### PR DESCRIPTION
**Pull request by woutslakhorst**
Screenshot 2022-03-31 at 14 32 48

### CODE REVIEW

**Comment by reinkrul** [comment]
"Stabile" -> "Stable"

**Review by reinkrul — CHANGES_REQUESTED** [review]
.

**Comment by gerardsn** [comment]
Juli -> July

**Comment by woutslakhorst** [comment]
Screenshot 2022-03-31 at 15 13 56

latest

**Review by reinkrul — APPROVED** [review]

**Pull request merged**
