### PR TITLE
Extend VCR an VDRv2 API clients

### PR DESCRIPTION
**Pull request by reinkrul**
Required by coming e2e browser test for EmployeeCredential.

Seperate PR to keep other PR smaller.

### CODE REVIEW

**Review by woutslakhorst — COMMENTED** [review]
Why do we need a client for this? I thought we're no longer investing in the command-line utilities?

**Comment by reinkrul** [comment]
> Why do we need a client for this? I thought we're no longer investing in the command-line utilities?

The HTTP client is used in the end-to-end test, which needs to specify the DID tenant. The CLI uses that HTTP client, and because its signature changed, the CLI needed to change.

**Comment by woutslakhorst** [comment]
> > Why do we need a client for this? I thought we're no longer investing in the command-line utilities?
> 
> The HTTP client is used in the end-to-end test, which needs to specify the DID tenant. The CLI uses that HTTP client, and because its signature changed, the CLI needed to change.

Why the addition of the `Load` method?

**Comment by reinkrul** [comment]
> > > Why do we need a client for this? I thought we're no longer investing in the command-line utilities?
> > 
> > 
> > The HTTP client is used in the end-to-end test, which needs to specify the DID tenant. The CLI uses that HTTP client, and because its signature changed, the CLI needed to change.
> 
> Why the addition of the `Load` method?

e2e test issues then loads a NutsOrganizationCredential.

**Comment by reinkrul** [comment]
> shouldn't the e2e-test be changed to load the credential through the API instead of investing in new CLI methods

I repeat:

>> Why do we need a client for this? I thought we're no longer investing in the command-line utilities?
> The HTTP client is used in the end-to-end test, which needs to specify the DID tenant. The CLI uses that HTTP client, and because its signature changed, the CLI needed to change.

If we don't want to change the CLI if the HTTP clients change, we need to remove the CLI.

**Comment by woutslakhorst** [comment]
@reinkrul it's ok to change the CLI for the changed API signature, but the `Load` method is new to the client and not used from the CLI.

**Comment by reinkrul** [comment]
> @reinkrul it's ok to change the CLI for the changed API signature, but the `Load` method is new to the client and not used from the CLI.

It's used by the browser test introduced by https://github.com/nuts-foundation/nuts-node/pull/3009

**Comment by woutslakhorst** [comment]
Hmmm, we have to discuss what to do with code only used for test but publicly exposed. Removing it would officially require a major update. I think we should consider moving all client API code to `internal`.

**Comment by reinkrul** [comment]
https://github.com/nuts-foundation/nuts-node/pull/3009 is also through, which includes this.

**Pull request closed without merging**
