### PR TITLE
Core: allow diagnostics to be retrieved in JSON format

### PR DESCRIPTION
**Pull request by reinkrul**
Fixes https://github.com/nuts-foundation/nuts-node/issues/468

Example JSON output:

```
{
  "Network": {
    "[DAG] Heads": [
      "d9217dfe685edc65e3b51303ce14292f6572140b197488bc3e8300d54792f017"
    ],
    "[DAG] Number of transactions": 664,
    "[DAG] Stored database size (bytes)": 0,
    "[P2P Network] Connected peers": [
      {
        "ID": "0c1b8600-b4b4-4c3f-a643-cfe84ebfc7a3",
        "Address": "128.199.61.173:39090"
      },
      {
        "ID": "799d1b42-2926-4a0d-bce4-f7e8abd38d77",
        "Address": "nuts.woutslakhorst.nl:5555"
      },
      {
        "ID": "b395c279-2b7d-4f99-9151-b98959635a99",
        "Address": "128.199.61.173:55114"
      },
      {
        "ID": "a5c2009e-f018-4102-9fd3-9738ea09487e",
        "Address": "89.184.189.226:48732"
      },
      {
        "ID": "3d2c4fb1-cc12-4a98-b7e8-d6897f5ae2c6",
        "Address": "128.199.61.173:39392"
      },
      {
        "ID": "ebbd8f0b-8cb6-466c-af29-95c6f3fcfd40",
        "Address": "128.199.61.173:50448"
      },
    
      {
        "ID": "93d2c3df-c339-4fd0-b696-82282a5cdbbd",
        "Address": "77.166.140.253:49644"
      },
      {
        "ID": "379f0009-3ced-48a6-9025-75ef99190230",
        "Address": "185.114.122.91:22834"
      }
    ],
    "[P2P Network] Connected peers #": 17,
    "[P2P Network] Peer ID of local node": "ccedd4e4-3f6b-4a2e-afe0-a81ea72d497a",
    "[Protocol] Missing Payload Hashes": null,
    "[Protocol] Peer omnihashes": {
      "0b9c68b9-04f1-469b-a242-18237e305a9d": "5dffebd68ffb0b5b45b80c88d376da87c369cc8c43083c4fcf026b3240b7f839",
      "0c1b8600-b4b4-4c3f-a643-cfe84ebfc7a3": "5dffebd68ffb0b5b45b80c88d376da87c369cc8c43083c4fcf026b3240b7f839",
      "379f0009-3ced-48a6-9025-75ef99190230": "5dffebd68ffb0b5b45b80c88d376da87c369cc8c43083c4fcf026b3240b7f839",
      "3d2c4fb1-cc12-4a98-b7e8-d6897f5ae2c6": "5dffebd68ffb0b5b45b80c88d376da87c369cc8c43083c4fcf026b3240b7f839",
      "ee9e7d1b-b622-4ec8-8aba-20236d883455": "5dffebd68ffb0b5b45b80c88d376da87c369cc8c43083c4fcf026b3240b7f839",
      "f4ca53d2-7771-4ff2-acc6-113a84c50688": "5dffebd68ffb0b5b45b80c88d376da87c369cc8c43083c4fcf026b3240b7f839",
      "fe8d0eb5-015c-458f-b342-4f40969cdc0c": "5dffebd68ffb0b5b45b80c88d376da87c369cc8c43083c4fcf026b3240b7f839"
    }
  },
  "Status": {
    "Git commit": "0",
    "OS/Arch": "linux/amd64",
    "Registered engines": [
      "Event manager",
      "Status",
      "Metrics",
      "Crypto",
      "Network",
      "Verifiable Data Registry",
      "Verifiable Credential Store",
      "Auth",
      "Didman"
    ],
    "SoftwareVersion": "master",
    "Uptime": 18000000000
  },
  "Verifiable Data Registry": {
    "# Conflicted DID Documents": 0
  }
}
```

### CODE REVIEW

**Comment by dmeijboom** [comment]
Would it make sense to remove the diagnostics in string format? I doubt it matters if it's always JSON right?

**Comment by reinkrul** [comment]
Not sure, there's probably no (or, not much) software built scraping the current text based diagnostics, but people are accustomed to reading it. I think readability of the diagnostics page is an important aspect.

At the same time we've got outstanding issues to improve the readability, so maybe we could switch to JSON altogether and return it pretty-printed?

Then people can both easily read it and we don't need to maintain the text-based variant.

**Comment by dmeijboom** [comment]
> so maybe we could switch to JSON altogether and return it pretty-printed?

I would be be in favour of that

**Comment by woutslakhorst** [comment]
I actually like my curl output to be just 15 lines, so I don't have to scroll.
For JSON, the keys are a bit verbose.

**Comment by reinkrul** [comment]
> I actually like my curl output to be just 15 lines, so I don't have to scroll. For JSON, the keys are a bit verbose.

There's 2 things  in the JSON output that trigger me:

1. We have some "subgroups" (`Network`) in text (e.g. `[DAG]`) which really should be a map (`dag`/`DAG`) in JSON
2. The keys are labels/descriptions, rather than technical keys.

The first one I'd like to fix in a subsequent PR, because that really alters the structure of the diagnostics types (this PR just adds an output type).

The second one, it's a trade-off between consistency (of text-based and JSON) and applicability (technical keys for JSON maps). What do you think @woutslakhorst @dmeijboom ?

**Comment by woutslakhorst** [comment]
> The second one, it's a trade-off between consistency (of text-based and JSON) and applicability (technical keys for JSON maps, e.g. engines v.s. "Registeres engines")

I think the descriptions in the TEXT output could be changed to keys as well without losing readability. 

```
"Verifiable Data Registry": {
    "# Conflicted DID Documents": 0
  }
```
Could be called: `vdr.conflicted_did_documents`:
```
"vdr": {
    "conflicted_did_documents": 0
  }
```
and
```
vdr
	conflicted_did_documents: 0
```

**Comment by reinkrul** [comment]
New output:

```json
{
  "network": {
    "dag_heads": [
      "5798fd903feeea169ae96c644be464ba9fd82c0204c9bf36c33ad1669a072fc0"
    ],
    "dag_stored_database_size_bytes": 0,
    "dag_transaction_count": 5,
    "p2p_connected_peers": null,
    "p2p_connected_peers_count": 0,
    "p2p_peer_id": "a2645563-103e-4fea-a080-da248027972a",
    "protocol_missing_payload_hashes": null,
    "protocol_peer_omnihashes": {}
  },
  "status": {
    "engines": [
      "Event manager",
      "Status",
      "Metrics",
      "Crypto",
      "Network",
      "VDR",
      "VCR",
      "Auth",
      "Didman"
    ],
    "git_commit": "0",
    "os_arch": "darwin/amd64",
    "software_version": "development",
    "uptime": 12000000000
  },
  "vdr": {
    "conflicted_did_documents_count": 0
  }
}
```

```
status
        engines: [Event manager Status Metrics Crypto Network VDR VCR Auth Didman]
        uptime: 14m27s
        software_version: development
        git_commit: 0
        os_arch: darwin/amd64
network
        protocol_peer_omnihashes: 
        protocol_missing_payload_hashes: []
        p2p_connected_peers_count: 0
        p2p_connected_peers: 
        p2p_peer_id: a2645563-103e-4fea-a080-da248027972a
        dag_heads: [5798fd903feeea169ae96c644be464ba9fd82c0204c9bf36c33ad1669a072fc0]
        dag_transaction_count: 5
        dag_stored_database_size_bytes: 0
vdr
        conflicted_did_documents_count: 0
```
```

**Comment by reinkrul** [comment]
Will have to fix the assertions in the end-to-end test after merging.

**Review by dmeijboom — APPROVED** [review]

**Review by woutslakhorst — APPROVED** [review]

**Pull request merged**
