### PR TITLE
Auth: Fixed returning wrapped errors

### PR DESCRIPTION
**Pull request by reinkrul**

### CODE REVIEW

**Review by woutslakhorst — COMMENTED** [review]
relation to #209?

**Comment by reinkrul** [comment]
> relation to #209?

Not fixed in that one, I kept it separate. Now I see I have conflicts, though.. :-p

**Review by woutslakhorst — CHANGES_REQUESTED** [review]
still conflicted. `auth/api/experimental/api.go` doesn't exist anymore

**Comment by reinkrul** [comment]
> still conflicted. `auth/api/experimental/api.go` doesn't exist anymore

Apparentely I forgot to push...

**Review by stevenvegt — APPROVED** [review]
Perhaps just removed the named return params and return the errors in the usual fasion?

**Review by woutslakhorst — APPROVED** [review]

**Review by woutslakhorst — APPROVED** [review]

**Pull request merged**
