### PR TITLE
removed deprecated services

### PR DESCRIPTION
**Pull request by woutslakhorst**
The old JWT tokens were only useable for a single Irma credential. Current contracts already require 2 credentials. So old stuff can be removed.

See #161 for some extra cleanup work

### CODE REVIEW

**Review by reinkrul — COMMENTED** [review]
I'm a bit confused, what replaced the IRMA contract signing session?

**Comment by woutslakhorst** [comment]
> I'm a bit confused, what replaced the IRMA contract signing session?

`CreateSignSession` in experimental. The removed one could only create a session for Irma, the new one does it for all means.

**Review by reinkrul — APPROVED** [review]

**Comment by reinkrul** [comment]
> > I'm a bit confused, what replaced the IRMA contract signing session?
> 
> `CreateSignSession` in experimental. The removed one could only create a session for Irma, the new one does it for all means.

Which means the new experimental API should become v1?

**Comment by woutslakhorst** [comment]
v0 and experimental should be merged to a single version. Which can still be v0 since this entire node is new.

**Comment by reinkrul** [comment]
> v0 and experimental should be merged to a single version. Which can still be v0 since this entire node is new.

Although I'd say let's just give all APIs we intend to keep for v1, version v1?

**Pull request merged**
