### PR TITLE
HTTP: specify Domain attribute in user session cookie

### PR DESCRIPTION
**Pull request by reinkrul**
Cookie is currently rejected by Safari/Firefox

Fixes https://github.com/nuts-foundation/nuts-node/issues/3164

### CODE REVIEW

**Comment by reinkrul** [comment]
@gerardsn would you mind testing this in Firefox or Safari?

**Comment by gerardsn** [comment]
Still the same `no credentials available` error in both.
- Safari console does not show any errors or cookies
- Firefox contains a cookie and has error: `Cookie ‘__Secure-SID’ met de ‘SameSite’-attribuutwaarde ‘Lax’ of ‘Strict’ is weggelaten vanwege een cross-site-doorgeleiding.`

**Comment by woutslakhorst** [comment]
> * cross-site-doorgeleiding

What's the english error?

**Comment by gerardsn** [comment]
dunno. I've set the OS and browser language to English but the error message does not change

**Comment by woutslakhorst** [comment]
@reinkrul should we close this for now?

**Comment by reinkrul** [comment]
I don't see much reason to fix this right now.

**Pull request closed without merging**
