### PR TITLE
elaborate on VC searching

### LINKED ISSUE #1133: Searching for a credential type should filter out other types
When searching for a credential, the type is used to expand the fields, but it's not used to filter out other types. So when a credential has matching fields but is from a different type, it still appears in the results. This is confusing.

### PR DESCRIPTION
**Pull request by woutslakhorst**
fixes #1133

### CODE REVIEW

**Review by reinkrul — COMMENTED** [review]
This might solve the issue for some who actually read and understand the documentation, but the API is still very counter-intuitive as a search API. Why not always filter out all other credentials which are not the specified type(s)?

**Comment by woutslakhorst** [comment]
> Why not always filter out all other credentials which are not the specified type(s) (maybe unless a flag is specified)?
because that's not how JSON-LD works. We must not encourage implementations to rely on specific type identifiers

**Comment by reinkrul** [comment]
> > Why not always filter out all other credentials which are not the specified type(s) (maybe unless a flag is specified)?
> > because that's not how JSON-LD works. We must not encourage implementations to rely on specific type identifiers

Then why do we have to specify specific type identifiers, if we musn't encourage implementations to rely on them? (don't answer; rhetorical question).

I understand that it makes sense from a JSON-LD point of view, but that doesn't make the search API any better. Imo it's naive to expect developers who'll be using the search API to understand the pecularities of JSON-LD and how its used when searching for VCs.

Nonetheless, given we don't change the API I think we need the docs as proposed by this PR.

But that doesn't make the search API any better. That said, the Nuts node might not be the right application to provide good DX (developer experience) for non-JSON LD-experts. Just like we introduced DIDMan (and maybe `Auth`), a domain-friendly search API might take the form of a `(Nuts) Registry` service deployed in front of a Nuts node.

**Review by reinkrul — APPROVED** [review]
See comment.

**Comment by woutslakhorst** [comment]
I believe DID SIOP has introduced a query language that is also used in OpenID-Connect4VP. That would be a solid future improvement.

**Pull request merged**
