### PR TITLE
Didman: remove redundant compound service validation

### PR DESCRIPTION
**Pull request by gerardsn**
validation now takes place in vdr.Update

invalid service error was previously incorrectly mapped to 406, is the specced 400 now

### CODE REVIEW

**Comment by gerardsn** [comment]
closes #1508

**Comment by stevenvegt** [comment]
Is there an issue for this?

**Comment by gerardsn** [comment]
This should have been part of #1769 and is the reason #1508 is not yet closed

**Comment by stevenvegt** [comment]
I think the response code for InvalidServiceError and the BadRequest are not tested?

**Review by woutslakhorst — CHANGES_REQUESTED** [review]
> I think the response code for InvalidServiceError and the BadRequest are not tested?

**Review by reinkrul — APPROVED** [review]

**Review by woutslakhorst — APPROVED** [review]

**Pull request merged**
