### PR TITLE
Return an empty payload for transactions that include a 'to' header in protocol v1

### PR DESCRIPTION
**Pull request by dmeijboom**

### CODE REVIEW

**Comment by woutslakhorst** [comment]
This one overlaps with #619?

**Comment by dmeijboom** [comment]
> This one overlaps with #619?

Yes, indeed

**Comment by woutslakhorst** [comment]
I'll wait for a rebase after #619 is merged.

**Comment by dmeijboom** [comment]
> I'll wait for a rebase after #619 is merged.

Voila ;)

**Review by woutslakhorst — APPROVED** [review]

**Pull request merged**
