### PR TITLE
Remove DID restore from restore procedure

### LINKED ISSUE #2324: Backup/restore documentation is incorrect
- it lists didstore.db as something that needs to be restored but also a reprocess of dids is mentioned.
- the did reprocess is also the last in the order, it should be the first.

At some point we decided on a basic set of things to restore, just because it was easier to just tell people to make a backup of the entire data dir. This was also reflected with the restore (1:1). Seems this is incorrect/weird now.

What do we want? Only restoring 1 or 2 db files when making a backup for 5 seems weird (although functionally correct). Restoring all from file is uniform but without a reprocess could be broken (because different db files get a backup at a different time)

### PR DESCRIPTION
**Pull request by woutslakhorst**
closes #2324 

With the removal of the DID reprocess, the docs are consistent again.

### CODE REVIEW

**Comment by reinkrul** [comment]
Clearer PR title please

**Comment by reinkrul** [comment]
We chose to have an additional store backed up (`vdr/didstore.db`) versus an extra reprocess (which got removed from docs). Why did we choose having an extra file to backup, instead of rebuilding it? The latter sounds more robust?

**Review by reinkrul — COMMENTED** [review]
See question

**Comment by gerardsn** [comment]
I think this is branching off of #2323? last commit is fine, but I will wait until that is merged to review this

**Comment by woutslakhorst** [comment]
> I think this is branching off of #2323? last commit is fine, but I will wait until that is merged to review this

oops

**Comment by woutslakhorst** [comment]
@gerardsn changed branch point

**Review by gerardsn — COMMENTED** [review]
step 3 is no longer needed either? (and part of step 11)

**Pull request merged**
