### PR TITLE
added security considerations page with single section on max upload sizes

### PR DESCRIPTION
**Pull request by woutslakhorst**

### CODE REVIEW

**Review by reinkrul — CHANGES_REQUESTED** [review]
Can we add this as subsection of https://nuts-node.readthedocs.io/en/latest/pages/deployment/recommended-deployment.html#proxy-api-gateway ?

**Comment by woutslakhorst** [comment]
> Can we add this as subsection of https://nuts-node.readthedocs.io/en/latest/pages/deployment/recommended-deployment.html#proxy-api-gateway ?

maybe link to or from, but I think a security considerations page must be top-level.

**Comment by reinkrul** [comment]
> > Can we add this as subsection of https://nuts-node.readthedocs.io/en/latest/pages/deployment/recommended-deployment.html#proxy-api-gateway ?
> 
> maybe link to or from, but I think a security considerations page must be top-level.

Then maybe move security considerations from that page (https://nuts-node.readthedocs.io/en/latest/pages/deployment/recommended-deployment.html#production-checklist) to the new one?

**Comment by woutslakhorst** [comment]
> Then maybe move security considerations from that page (https://nuts-node.readthedocs.io/en/latest/pages/deployment/recommended-deployment.html#production-checklist) to the new one?

Better to move some of those points to the new page, yes.

**Pull request merged**
