### PR TITLE
Docs: add nodedid to backup-restore procedure

### LINKED ISSUE #1927: VDR: private transactions fail if the node's DID document cannot be found
strict mode + unable find the node's own DID document is a fatal error that kills the node. 

In non-strict mode it is not fatal, which results in: cannot find own DID doc -> don't know if private transactions is addressed to me -> a failed event for every private transaction. This also clutters the diagnostics page with these messages:

```
- type: transaction
  hash: e4f301b21c7b2dc04917c60eb55f84dba1d9677425a78c220e7dac90dd74fdc4
  retries: 101
  latest: 2023-02-25T09:47:28.48363339Z
  transaction: {}
  payload: []
  error: 'failed to decrypt PAL header (tx=e4f301b21c7b2dc04917c60eb55f84dba1d9677425a78c220e7dac90dd74fdc4): unable to find the DID document'
```

This can occur when the configured DID is incorrect, or in my case, I deleted `network/data.db` (DAG) + `vdr/didstore.db` (VDR) to trigger resynchronization but left the `NodeDID` in the config.

### PR DESCRIPTION
**Pull request by gerardsn**
closes #1927

### CODE REVIEW

**Review by reinkrul — APPROVED** [review]

**Review by reinkrul — APPROVED** [review]

**Comment by gerardsn** [comment]
The node must be kept offline during the reprocess procedure. This requires changing 4 fields in the network config (`bootstrapnodes`, `grpcaddr`, and `nodedid` must be empty, and `enablediscovery==false`). Those changes need to reverted after the reprocess is complete to get the node back into production mode.

- Adding a `network.offline` config flag that automatically applies the above changes and seems like a user friendlier approach than the current flow
- The only indication that the reprocess is complete (signal to restart) is a recently added log message that is not in a tagged version yet

**Comment by woutslakhorst** [comment]
> Adding a network.offline config flag that automatically applies the above changes and seems like a user friendlier approach than the current flow

An API to change the state of the node to offline might be a more friendly approach?

**Comment by reinkrul** [comment]
Reprocess should take node offline until it finishes?

**Comment by gerardsn** [comment]
An API is nicer but also requires a larger change

Hypothesizing what it would need

**logic**
- kill protocols and connection manager to close all connections and take the network offline
- add status to `/health`
- status at startup can be configured with `network.offline` (if not offline at startup you would still have to remove the nodeDID from the config in a backup-restore procedure)
- disallow any API call that creates data published to the network? (OpenID flow can still work?)

**API**
- single endpoint
- POST to change status
- GET returns status for load balancer grpc health check?

**Comment by gerardsn** [comment]
Taking the node offline for a reprocess requires much of the same logic. It feels prone to errors if you request to reprocess multiple types at the same time. What determines when it goes back online? We may end up with the API anyway to fix the status.

**Comment by gerardsn** [comment]
Created #2149 to continue the discussion, and merging this as it describes the current situation

**Pull request merged**
